private_key: !!binary |
  CAASqQkwggSlAgEAAoIBAQDoIQyLx/lLXtjllgg59kScAxXTVFZyJxBulpEadeXNU+OIR/
  wu+rWnhxKvqhbG0lLa0lUI1bSoM7xxbHYHJHK9ad+aYiLfumrkEJS1wn1tI1mzehef/655
  YXXYSNLL3Cvw4yFPZR55/EAtfkY3URsr4m5MMoyfclr3pcC2bEFkGPWnRTDKWN57XYnHW9
  mew59PVycdzMQ2mRhY4OiR+mw4bAs4RkYssWU5IlbguwFBREPG5lrCFFJnm66V4UARwu0S
  sOOYe2ASVe6Tq8m5OZHzLRf9h4w52q4E2vp2JNZz4QnyXb+scBrOoHc/VIyfOAJkBOsF6W
  gJ9zywgM3H5PP1AgMBAAECggEBAIzxBB0bHlKVFDzSC8ylqqLPfMEDxDkrXt7GrPPUAePZ
  u51Tl9sufn1plf7y10GBEq2qZ9clart2LkTwBfnwN3qqfgnO7D3LgntXVfPGU0Gg5SYES7
  PqGpW4h0T7coI0/LkWL3N1gjuu3YjB0wBjTowmv7GkP53QYUtcaNZahJmxJepcdrkAVJem
  AG9GdswaVIG7EFekmeT90lo5zKVG2tzCRKgxZjHEdU7YMD/4u5CIR5OmepqEqy8ySCrRHn
  O13nWSrG3MovDPoFpdKBbOqhgqOnGhnxfwDQEzOvMlkzgNFb0Qz195AiVccnOV4RC3D87i
  78DcUiyg8qKOeqjIagECgYEA9rb8IDXVC1sgltNjtJxmmQk/9YmThsZh3L7cbsqxZr/WR8
  Xb5qndaSbrRrWoDQBYa4GYK5rIi9JjoMobYexTA2Qk+rwtGpkuIzeStWZ4T0mkvdMQKNwE
  NTvvC22who0Mn3dGPMo81MUNeoB4WGAzWH/uCFFGRkahWur292+e3IkCgYEA8N2JL7v/KB
  lgTogMfJczVPERnzAJKMohrA7frwB+plXqDu8iVCr0rCwRZQmP8jz8KMrTMBLRCkoXr1Hw
  1ccEiZHR/uK7ex5z9X+6xmAyLLFuSvVGLjDB9LX64lS52vuEjWncCZ/AzJWTPu7GP7uEgY
  CIiOvwUFXK0jSzi0IfeQ0CgYEA1u9NsaYUZ6NJPf0FpQiInZSgYwIrQ0Q7Z7vjgKYXbUN9
  o+OtE0QzP3OHj3+c207MuUQa1Qow4xc0cpUAzAu9unuZd9NOnBiNSGMW7fBKqhCndDSXpH
  EhPVtsgxFZs67YK2kXCMjLvDW761hW/+83bEdvkVF1Hq5TzkhbRe+5f7kCgYEAwfn3oHyr
  aXS+TaBdRf1StqaKBYRe6/2VDobP95TTakuoeqx1HgmWEA5RV+hSh8g7XvKxD3cn6DxxRJ
  0d8lwbuFq6HqYkTGvjASQDm/0ei0W9SBqtkUds/BGOYbXQE54ZSvWk4g9I6rnO4pDTEcKH
  XO/RhUtVtqzQ8WbF7XGr/QUCgYATyo8nhxTG5a39+NsLTpGJBq6yZ/YGNQPALPKy783yYw
  ZN8itOScl5EceXtCBpT1gc+hSNZxtuKtLDdeXw5p9WYyHaDNpzgKLapB7LkkmQviwVfdpu
  YZ6EvR6z3Qpj+Xnh/yd/yp9ET9HiOOf343CpAJJ3KFoCjKKEe184Q9nb4Q==
